#samples.yaml for mutect2.snakefile

base_file_name: 
  DTRCC3_Rkidney: /mnt/storage/labs/sviswanathan/tRCC_data/FFPE/WGS/DTRCC3_Rkidney/v3/DTRCC3_Rkidney.cram
  DTRCC_3_Blood: /mnt/storage/labs/sviswanathan/tRCC_data/FFPE/normal/WGS/DTRCC_3_Blood/v1/DTRCC_3_Blood.cram
  DTRCC_4_Blood: /mnt/storage/labs/sviswanathan/tRCC_data/FFPE/normal/WGS/DTRCC_4_Blood/v1/DTRCC_4_Blood.cram
  DTRCC4_LUL: /mnt/storage/labs/sviswanathan/tRCC_data/FFPE/WGS/DTRCC4_LUL/v3/DTRCC4_LUL.cram
  DTRCC7_Rkidney: /mnt/storage/labs/sviswanathan/tRCC_data/FFPE/WGS/DTRCC7_Rkidney/v1/DTRCC7_Rkidney.cram
  DTRCC7_Nkidney: /mnt/storage/labs/sviswanathan/tRCC_data/FFPE/normal/WGS/DTRCC7_Nkidney/v1/DTRCC7_Nkidney.cram
  DTRCC9_Rkidney: /mnt/storage/labs/sviswanathan/tRCC_data/FFPE/WGS/DTRCC9_Rkidney/v1/DTRCC9_Rkidney.cram
  DTRCC_9_Blood: /mnt/storage/labs/sviswanathan/tRCC_data/FFPE/normal/WGS/DTRCC_9_Blood/v1/DTRCC_9_Blood.cram

normals:
  DTRCC3_Rkidney: DTRCC_3_Blood
  DTRCC4_LUL: DTRCC_4_Blood
  DTRCC7_Rkidney: DTRCC7_Nkidney
  DTRCC9_Rkidney: DTRCC_9_Blood
  
