#samples.yaml for mutect2.snakefile

base_file_name: 
  DTRCC6_LKidneyResection: /mnt/storage/labs/sviswanathan/tRCC_data/DTRCC_6/DTRCC6_LKidneyResection.linkedReads.bam
  DTRCC6_AdjNormal: /mnt/storage/labs/sviswanathan/tRCC_data/DTRCC_6/DTRCC6_AdjNormal.linkedReads.bam
  DTRCC8_Lkidney: /home/mi724/Tools/Mutect2_Snakemake/linked_reads/DTRCC8_Lkidney.bam.list
  DTRCC10_Rkidney: /home/mi724/Tools/Mutect2_Snakemake/linked_reads/DTRCC10_Rkidney.bam.list

normals:
  DTRCC6_LKidneyResection: DTRCC6_AdjNormal
  DTRCC8_Lkidney: DTRCC_8_Blood
  DTRCC10_Rkidney: DTRCC_10_Blood
  
