__default__:
    q:  broad
    h_vmem: 20G
    h_rt:   100:0:0
    pe: smp 4
    binding:    linear:1

LearnReadOrientationModel:
    q:  broad
    h_vmem: 30G
    h_rt:   300:0:0
    pe: smp 8
    binding:    linear:1
