#samples.yaml for mutect2.snakefile

base_file_name: 
  tRCC_26_N: /mnt/scratch/qu_random/test/tRCC_26_N_hg38_sorted_picard.bam
  tRCC_72_N: /mnt/scratch/qu_random/test/tRCC_72_N_hg38_sorted_picard.bam

normals:
  tRCC_26_N: tRCC_26_N
  tRCC_72_N: tRCC_72_N
