#samples.yaml for mutect2.snakefile

base_file_name:
  ccle_786O: /mnt/storage/labs/sviswanathan/tRCC_data/trcc_wes/bam_run/ccle_786O_rg_sorted.bam
  ccle_caki1: /mnt/storage/labs/sviswanathan/tRCC_data/trcc_wes/bam_run/ccle_caki1_rg_sorted.bam
  
normals:
  ccle_786O: 786O_KIDNEY
  ccle_caki1: CAKI1_KIDNEY
  
