#samples.yaml for mutect2.snakefile

base_file_name: 
  DTRCC19_kidney: /mnt/storage/labs/sviswanathan/tRCC_data/DTRCC19_kidney
  DTRCC19_AdjNormal: /mnt/storage/labs/sviswanathan/tRCC_data/DTRCC19_AdjNormal

normals:
  DTRCC19_kidney: DTRCC19_AdjNormal
